services:
  postgres:
    image: postgres:16
    container_name: fraud-shield-postgres
    environment:
      POSTGRES_DB: fraud_shield
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - fraud_shield_postgres_data:/var/lib/postgresql/data

volumes:
  fraud_shield_postgres_data: